### ISSUE TITLE
NPE in Fluent Builder Plugin

### ISSUE THREAD

**Issue by torkeld** [mklemm/jaxb2-rich-contract-plugin#10]
Hi Mirko,

Thanks for a great plugin!
I'm getting a NPE when trying to generate classes with the fluent-builder option from the MSML language (Media Server Markup Language, RFC 5707).
Trying with a simple schema works fine.
I'm running this from maven, and the same input works fine with just the maven-jaxb2-plugin plugin (without jaxb2-rich-contract-plugin).
I'm using version 1.3.0 together with maven-jaxb2-plugin version 0.12.3.

Here is the output from maven:

[INFO] Parsing input schema(s)...
[DEBUG] Resolving publicId [http://www.w3.org/XML/1998/namespace], systemId [http://www.w3.org/2001/xml.xsd].
resolveSystem(http://www.w3.org/2001/xml.xsd)
resolvePublic(http://www.w3.org/XML/1998/namespace,http://www.w3.org/2001/xml.xsd)
[DEBUG] Parent resolver has resolved publicId [http://www.w3.org/XML/1998/namespace], systemId [http://www.w3.org/2001/xml.xsd] to [null].
[DEBUG] SystemId [http://www.w3.org/2001/xml.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
[DEBUG] Resolving publicId [null], systemId [synthesis-core.xsd].
resolveSystem(synthesis-core.xsd)
[DEBUG] Parent resolver has resolved publicId [null], systemId [synthesis-core.xsd] to [null].
[DEBUG] SystemId [synthesis-core.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
[DEBUG] Resolving publicId [null], systemId [http://www.w3.org/2001/xml.xsd].
resolveSystem(http://www.w3.org/2001/xml.xsd)
[DEBUG] Parent resolver has resolved publicId [null], systemId [http://www.w3.org/2001/xml.xsd] to [null].
[DEBUG] SystemId [http://www.w3.org/2001/xml.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
[DEBUG] Resolving publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/moml-datatypes.xsd].
resolveSystem(file:/Users/tdominique/Development/git/msml/src/main/resources/moml-datatypes.xsd)
[DEBUG] Parent resolver has resolved publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/moml-datatypes.xsd] to [null].
[DEBUG] SystemId [file:/Users/tdominique/Development/git/msml/src/main/resources/moml-datatypes.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
[DEBUG] Resolving publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/msml-datatypes.xsd].
resolveSystem(file:/Users/tdominique/Development/git/msml/src/main/resources/msml-datatypes.xsd)
[DEBUG] Parent resolver has resolved publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/msml-datatypes.xsd] to [null].
[DEBUG] SystemId [file:/Users/tdominique/Development/git/msml/src/main/resources/msml-datatypes.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
[DEBUG] Resolving publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/moml-core-module.xsd].
resolveSystem(file:/Users/tdominique/Development/git/msml/src/main/resources/moml-core-module.xsd)
[DEBUG] Parent resolver has resolved publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/moml-core-module.xsd] to [null].
[DEBUG] SystemId [file:/Users/tdominique/Development/git/msml/src/main/resources/moml-core-module.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
[DEBUG] Resolving publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/nlsml-core.xsd].
resolveSystem(file:/Users/tdominique/Development/git/msml/src/main/resources/nlsml-core.xsd)
[DEBUG] Parent resolver has resolved publicId [null], systemId [file:/Users/tdominique/Development/git/msml/src/main/resources/nlsml-core.xsd] to [null].
[DEBUG] SystemId [file:/Users/tdominique/Development/git/msml/src/main/resources/nlsml-core.xsd] is not a Maven dependency resource URI. Returning parent resolver result [null].
[INFO] Compiling input schema(s)...
Jan 05, 2015 10:07:04 PM com.kscs.util.plugins.xjc.SelectorGenerator generateMetaClass
WARNING: Attempt to generate already existing class
Jan 05, 2015 10:07:04 PM com.kscs.util.plugins.xjc.SelectorGenerator generateMetaClass
WARNING: Attempt to generate already existing class
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.689 s
[INFO] Finished at: 2015-01-05T22:07:04-08:00
[INFO] Final Memory: 16M/180M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate (xsd-generate-2.2) on project msml: Execution xsd-generate-2.2 of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate (xsd-generate-2.2) on project msml: Execution xsd-generate-2.2 of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution xsd-generate-2.2 of goal org.jvnet.jaxb2.maven2:maven-jaxb2-plugin:0.12.3:generate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at com.kscs.util.plugins.xjc.SelectorGenerator.generateMetaFields(SelectorGenerator.java:123)
	at com.kscs.util.plugins.xjc.FluentBuilderPlugin.run(FluentBuilderPlugin.java:114)
	at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.generateCode(XJC22Mojo.java:66)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:41)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:488)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:311)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	... 20 more

I've received the xsd files from Radisys so I'm not sure I'm allowed to forward them to you, but I'm happy to tests any potential fixes.

Thanks,
Torkel

**Comment by torkeld** [comment]
Turned out to be a naming conflict. One of the types in the schema had an element called "selector". This pull request resolved the problem for me: https://github.com/mklemm/jaxb2-rich-contract-plugin/pull/11

**Comment by mklemm** [comment]
Hi torkeId,
Version 1.5.2 is planned with support for customizing the names of generated source elements via command-line or JAXB binding customizations.
This should enable you to resolve naming conflicts like this. I'll keep you posted on the progress.

**Comment by mklemm** [comment]
Version 1.5.2 has been released on Maven central. Many generated names in source code can now be customized via command-line options. Please note: The groupId had to change to com.klemm-scs.util because of Sonatype Central hosting requirements.
