### ISSUE TITLE
Error with jaxws-maven-plugin

### ISSUE THREAD

**Issue by msglaser** [mklemm/jaxb2-rich-contract-plugin#15]
When using the Version 1.5.4 of jabx2-rich-contract-plugin within jaxws-maven-plugin as show below, the following error occurs (full stacktrace at the end):
Exception in thread "main" java.lang.ClassCastException: java.lang.ExceptionInInitializerError cannot be cast to java.lang.Exception
	at org.jvnet.jax_ws_commons.jaxws.Invoker.main(Invoker.java:87)

With the version 1.3.0 this worked perfect. Unforunately, I cannot test the version 1.4.0 as I could not find this version in the maven-repo.
_____________________________________________________________________________
	<build>
		<plugins>

			<plugin>
				<groupId>org.jvnet.jax-ws-commons</groupId>
				<artifactId>jaxws-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>net.codesup.util</groupId>
						<artifactId>jaxb2-rich-contract-plugin</artifactId>
						<version>1.5.4</version>
					</dependency>
				</dependencies>
				<configuration>
					<wsdlDirectory>src/main/resources/wsdl</wsdlDirectory>
				</configuration>
				<executions>
					<execution>
						<id>WSDL</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>wsimport</goal>
						</goals>
						<configuration>
							<verbose>true</verbose>
							
							<packageName>xyz</packageName>
							<wsdlFiles>
								<wsdlFile>xyz.wsdl</wsdlFile>
							</wsdlFiles>
							<args>
								<arg>-B-Xfluent-builder</arg>
							</args>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

____________________________________________________________________________
full stacktrace:

java.lang.NoSuchMethodException: com.sun.xml.bind.v2.model.nav.ReflectionNavigator.getInstance()
	at java.lang.Class.getDeclaredMethod(Class.java:2004)
	at com.sun.xml.bind.v2.model.impl.Utils.<clinit>(Utils.java:71)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:92)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:444)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:292)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1138)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:262)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:249)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:442)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:652)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationContext(BindInfo.java:336)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationUnmarshaller(BindInfo.java:362)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl$1.<init>(AnnotationParserFactoryImpl.java:85)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl.create(AnnotationParserFactoryImpl.java:84)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.createAnnotationParser(NGCCRuntimeEx.java:365)
	at com.sun.xml.xsom.impl.parser.state.annotation.action0(annotation.java:88)
	at com.sun.xml.xsom.impl.parser.state.annotation.enterElement(annotation.java:113)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:113)
	at com.sun.xml.xsom.impl.parser.state.complexType.enterElement(complexType.java:210)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromEnterElement(NGCCHandler.java:150)
	at com.sun.xml.xsom.impl.parser.state.foreignAttributes.enterElement(foreignAttributes.java:90)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:113)
	at com.sun.xml.xsom.impl.parser.state.complexType.enterElement(complexType.java:579)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.complexType.enterElement(complexType.java:342)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.complexType.enterElement(complexType.java:455)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.complexType.enterElement(complexType.java:238)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.complexType.enterElement(complexType.java:432)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:417)
	at com.sun.xml.xsom.impl.parser.state.complexType.enterElement(complexType.java:369)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.startElement(NGCCRuntime.java:258)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc.util.SubtreeCutter.startElement(SubtreeCutter.java:108)
	at com.sun.tools.xjc.reader.ExtensionBindingChecker.startElement(ExtensionBindingChecker.java:150)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.startElement(IncorrectNamespaceURIChecker.java:128)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.startElement(CustomizationContextChecker.java:193)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.startElement(DOMForestScanner.java:147)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:244)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:281)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:250)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:281)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:250)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:92)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:100)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:104)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.importSchema(NGCCRuntimeEx.java:258)
	at com.sun.xml.xsom.impl.parser.state.importDecl.action0(importDecl.java:85)
	at com.sun.xml.xsom.impl.parser.state.importDecl.leaveElement(importDecl.java:183)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:314)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.util.SubtreeCutter.endElement(SubtreeCutter.java:112)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement(CustomizationContextChecker.java:199)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.endElement(DOMForestScanner.java:140)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:255)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:281)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:250)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:92)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:100)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:104)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.importSchema(NGCCRuntimeEx.java:258)
	at com.sun.xml.xsom.impl.parser.state.importDecl.action0(importDecl.java:85)
	at com.sun.xml.xsom.impl.parser.state.importDecl.leaveElement(importDecl.java:183)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:314)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.util.SubtreeCutter.endElement(SubtreeCutter.java:112)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement(CustomizationContextChecker.java:199)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.endElement(DOMForestScanner.java:140)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:255)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:281)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:250)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:92)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:100)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:104)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:128)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:168)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:157)
	at com.sun.tools.xjc.ModelLoader.createXSOM(ModelLoader.java:534)
	at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:269)
	at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:95)
	at com.sun.tools.ws.processor.modeler.wsdl.JAXBModelBuilder.bind(JAXBModelBuilder.java:142)
	at com.sun.tools.ws.processor.modeler.wsdl.WSDLModeler.buildJAXBModel(WSDLModeler.java:2298)
	at com.sun.tools.ws.processor.modeler.wsdl.WSDLModeler.internalBuildModel(WSDLModeler.java:198)
	at com.sun.tools.ws.processor.modeler.wsdl.WSDLModeler.buildModel(WSDLModeler.java:141)
	at com.sun.tools.ws.wscompile.WsimportTool.buildWsdlModel(WsimportTool.java:444)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:205)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jvnet.jax_ws_commons.jaxws.Invoker.main(Invoker.java:73)

**Comment by mklemm** [comment]
Hi,
it in the stack trace, I cannot see any method call into the jaxb2-rich-contract-plugin. BUT: It seems I have seen a similar error before. There may be an incompatibility in the JAXB versions used while generating the source code. Have you tried adding a newer JAXB version to the dependencies of the jaxws-maven-plugin? The thing is, the plugin pulls in JAXB 2.2.11 as its own dependency, and this may conflict with the jaxws-maven-plugin version you have. I’d suggest you try one of the following:
- Upgrade to a newer version of the jaxws-maven-plugin, if available OR
- <exclude> the dependencies to JAXB 2.2.11 from the <dependencies> section of the jaxws plugin.

Please let me know if this helped you.
Regards,
Mirko

**Comment by msglaser** [comment]
Hi Mirko
I use the version 2.3 of the jaxws-maven-plugin. This is the latest version so far. But I tried with version 2.2 and it works with that.
I also tried the second options to exclude the jaxb-dependencies from the jaxb2-rich-contract-plugin. With that it works also fine.
Rather than using an older version, I decided to work with the exclusion.
Tks for your help.
/Markus
