### ISSUE TITLE
ConcurrentModificationException with -constructorAccess

### ISSUE THREAD

**Issue by haxney** [mklemm/jaxb2-rich-contract-plugin#18]
I'm using `-Ximmutable` with a `-constructorAccess` argument to try to create non-public constructors for a schema. If I try to set `-constructorAccess` to anything other than `public` (the default), I get the following exception:

```
Exception in thread "main" java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
        at java.util.ArrayList$Itr.next(ArrayList.java:831)
        at com.kscs.util.plugins.xjc.ImmutablePlugin.run(ImmutablePlugin.java:113)
        at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
        at com.sun.tools.xjc.Driver.run(Driver.java:384)
        at com.sun.tools.xjc.Driver.run(Driver.java:221)
        at com.sun.tools.xjc.Driver._main(Driver.java:144)
        at com.sun.tools.xjc.Driver.access$000(Driver.java:82)
        at com.sun.tools.xjc.Driver$1.run(Driver.java:103)
```

I am invoking xjc like this:

```
mkdir /tmp/jaxb-gen

java \
-classpath jaxb-api.jar:jaxb-core.jar:jaxb-impl.jar:jaxb-jxc.jar:jaxb-xjc.jar \
com.sun.tools.xjc.XJCFacade \
-extension \
-d /tmp/jaxb-gen \
-classpath jaxb2-rich-contract-plugin.jar \
-Xfluent-builder \
-Ximmutable \
-constructorAccess=private \
soap-envelope.xsd
```

Where `soap-envelope.xsd` is [this file](http://schemas.xmlsoap.org/soap/envelope/).

Removing the `-constructorAccess=private` line or replacing it with `-constructorAccess=public` makes the compilation work.

I am using jaxb2-rich-contract-plugin version 1.6.7 with JAXB 2.2.11 on Java 7.

**Comment by mklemm** [comment]
Fixed in 1.9.0
