### ISSUE TITLE
Errors when generating sources for complex XSD

### ISSUE THREAD

**Issue by Vikciux** [mklemm/jaxb2-rich-contract-plugin#28]
I get multiple exceptions of few types, when trying to generate sources from the XSD located in:
http://www.s3000l.org/docs/s3000l_1-1_XML_schema_001-00.zip

I use org.codehaus.mojo:jaxb2-maven-plugin:2.2 plugin and version 1.17.0 of jaxb2-rich-contract-plugin. Invoking like this:

```
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>2.2</version>
                <executions>
                    <execution>
                        <id>xjc</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <arguments>
                        <argument>-Xgroup-contract</argument>
                    </arguments>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.codesup.util</groupId>
                        <artifactId>jaxb2-rich-contract-plugin</artifactId>
                        <version>1.17.0</version>
                    </dependency>
                </dependencies>
            </plugin>

```

============== Error 1:

```
org.xml.sax.SAXParseException; systemId: file:/project/src/main/xsd/s3000l_1-1_lsa_dataset.xsd; lineNumber: 4906; columnNumber: 88; Property "dt element declaration" declared by schema component "Dt" not found in interface "org.asd_europe.s_series.s3000l.DownTime"
    at com.kscs.util.plugins.xjc.GroupInterfaceGenerator.findField(GroupInterfaceGenerator.java:531)
    at com.kscs.util.plugins.xjc.GroupInterfaceGenerator.createInterfaceDeclaration(GroupInterfaceGenerator.java:509)
    at com.kscs.util.plugins.xjc.GroupInterfaceGenerator.generateGroupInterfaces(GroupInterfaceGenerator.java:317)
    at com.kscs.util.plugins.xjc.GroupInterfaceGenerator.generateGroupInterfaceModel(GroupInterfaceGenerator.java:353)
    at com.kscs.util.plugins.xjc.GroupInterfacePlugin.generate(GroupInterfacePlugin.java:146)
    at com.kscs.util.plugins.xjc.GroupInterfacePlugin.run(GroupInterfacePlugin.java:131)
    at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
...


```

============== Error 2:

```
org.xml.sax.SAXParseException; systemId: file:/project/src/main/xsd/s3000l_1-1_lsa_dataset.xsd; lineNumber: 4690; columnNumber: 36; Interface SamplingItem, defined by group declaration {http://www.asd-europe.org/s-series/s3000l}samplingItem has no implementation.
    at com.kscs.util.plugins.xjc.GroupInterfaceGenerator.createInterfaceDeclaration(GroupInterfaceGenerator.java:467)
    at com.kscs.util.plugins.xjc.GroupInterfaceGenerator.generateGroupInterfaces(GroupInterfaceGenerator.java:317)
    at com.kscs.util.plugins.xjc.GroupInterfaceGenerator.generateGroupInterfaceModel(GroupInterfaceGenerator.java:353)
    at com.kscs.util.plugins.xjc.GroupInterfacePlugin.generate(GroupInterfacePlugin.java:146)
    at com.kscs.util.plugins.xjc.GroupInterfacePlugin.run(GroupInterfacePlugin.java:131)
    at com.sun.tools.xjc.model.Model.generateCode(Model.java:292)
...


```

On the first glance the XSD looks correct, but perhaps I'm missing something.

**Comment by mklemm** [comment]
Hi,
Unfortunately, I'm unable to reproduce your issues because the XSDs you added seem to have errors - some types cannot be found.
I'd recommend you don't use the org.codehaus.mojo jaxb2-maven-plugin, but instead go for the org.jvnet.jaxb2.maven2:maven-jaxb2-plugin in a recent version.

**Comment by Vikciux** [comment]
Unfortunately the org.jvnet.jaxb2.maven2:maven-jaxb2-plugin reports errors while parsing XSD, but the errors in my opinion are non existent. For example it reports, that "'correctionFactor' is already defined", but I do not see a problem with that, as once it is defined as group and another time as simpleName. Thus it is defined multiple times, but in different symbol spaces*. Of course it might be, that this error means something else, but I do not see what else it could mean.

Is your plug-in not supported to be used with org.codehaus.mojo plug-in?

* see https://www.w3.org/TR/xmlschema11-1/#concepts-nameSymbolSpaces

**Comment by Vikciux** [comment]
So I've managed to create a minimal XSD, that gets compiled without a problem using org.jvnet.jaxb2.maven2:maven-jaxb2-plugin, but does not compile when using jaxb2-rich-contract-pluginwith arg -Xgroup-contract.

Here is the schema:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.example.com/xsd" targetNamespace="http://www.example.com/xsd">

	<xsd:element name="element">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:group ref="correctionFactor" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

    <xsd:group name="correctionFactor">
        <xsd:sequence>
            <xsd:element name="corrFact" minOccurs="0" maxOccurs="unbounded" nillable="true">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="factor" type="correctionFactor"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:group>

    <xsd:simpleType name="correctionFactor">
        <xsd:restriction base="xsd:decimal"/>
    </xsd:simpleType>
</xsd:schema>
```

Here are the errors:

`[INFO] Parsing input schema(s)...
[ERROR] Error while parsing schema(s).Location [ file:/test-xsd/src/main/alt/edu-impl.xsd{1,464}].
org.xml.sax.SAXParseException; systemId: file:/test-xsd/src/main/alt/edu-impl.xsd; lineNumber: 1; columnNumber: 464; 'correctionFactor' is already defined
	at com.sun.xml.xsom.impl.parser.ParserContext$1.reportError(ParserContext.java:180)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:175)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:178)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.checkDoubleDefError(NGCCRuntimeEx.java:150)
	at com.sun.xml.xsom.impl.parser.state.Schema.action5(Schema.java:127)
	at com.sun.xml.xsom.impl.parser.state.Schema.onChildCompleted(Schema.java:1222)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromText(NGCCHandler.java:183)
	at com.sun.xml.xsom.impl.parser.state.complexType.text(complexType.java:1712)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.processPendingText(NGCCRuntime.java:236)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:312)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.util.SubtreeCutter.endElement(SubtreeCutter.java:112)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement(CustomizationContextChecker.java:199)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.endElement(DOMForestScanner.java:140)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:255)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:92)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:100)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:104)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:128)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:171)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:160)
	at com.sun.tools.xjc.ModelLoader.createXSOM(ModelLoader.java:534)
	at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:378)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Error while parsing schema(s).Location [ file:/test-xsd/src/main/alt/edu.xsd{24,45}].
org.xml.sax.SAXParseException; systemId: file:/test-xsd/src/main/alt/edu.xsd; lineNumber: 24; columnNumber: 45; (related to above error) the first definition appears here
	at com.sun.xml.xsom.impl.parser.ParserContext$1.reportError(ParserContext.java:180)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:175)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.checkDoubleDefError(NGCCRuntimeEx.java:151)
	at com.sun.xml.xsom.impl.parser.state.Schema.action5(Schema.java:127)
	at com.sun.xml.xsom.impl.parser.state.Schema.onChildCompleted(Schema.java:1222)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromText(NGCCHandler.java:183)
	at com.sun.xml.xsom.impl.parser.state.complexType.text(complexType.java:1712)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.processPendingText(NGCCRuntime.java:236)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:312)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.util.SubtreeCutter.endElement(SubtreeCutter.java:112)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement(CustomizationContextChecker.java:199)
	at org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.endElement(DOMForestScanner.java:140)
	at com.sun.xml.bind.unmarshaller.DOMScanner.visit(DOMScanner.java:255)
	at com.sun.xml.bind.unmarshaller.DOMScanner.scan(DOMScanner.java:127)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:92)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:100)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:104)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:269)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:347)
	at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:128)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:171)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:160)
	at com.sun.tools.xjc.ModelLoader.createXSOM(ModelLoader.java:534)
	at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:378)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
...
`

**Comment by mklemm** [comment]
Technically, your XSD is correct, but it cannot be processed by XJC in the current form, since both the simpleType and the group are compiled to equally-named Java constructs. In Java, an Identifier for a class or interface can only exist once in the same package.
I suggest you try renaming the simpleType by adding an xjc binding customization element to it that specifies a different Java name.
